[rpc]
address = "http://localhost:26657"

[grpc]
address = "localhost:9090"

[lcd]
address = "http://localhost:1317"

[coinmarketcap]
api_key = "<YOUR_API_KEY>"

[wallet]
mnemonic = "<YOUR_MNEMONIC>"

[firestation]
cmc_id_a = "3794" # ATOM 
cmc_id_b = "4172" # LUNA
denom_a = "uatom"
denom_b = "uluna"