[rpc]
address = "http://localhost:26657"

[grpc]
address = "localhost:9090"

[lcd]
address = "http://localhost:1317"

[coinmarketcap]
api_key = "<YOUR_API_KEY>"

[wallet]
mnemonic = "<YOUR_MNEMONIC>"

[firestation]
fee_denom = "stake"
fee_amount = 10000000